config/routes.rb
Rails.application.routes.draw do

  post 'ground_routes/import' => 'ground_routes#import'
  get 'ground_routes/index' => 'ground_routes#index'
  root 'ground_routes#index'

end

app/models/airport.rb
class Airport
    attr_reader :ground_routes
    
    def initialize(file)
        @document = Nokogiri::HTML(file)
        @ground_routes = []
        read_routes
    end
    
    private
    
    def read_routes
        @document.xpath("//hierarchy").each do |xmlnode|
            next unless xmlnode.attribute('name')
                               .to_s.match(/^(dep|arr)\p{Blank}*:/i)
            @ground_routes << GroundRoute.new(xmlnode, @document)
        end
    end
end

app/models/ground_route.rb
# route name
# <DEP|ARR>:<RWY> spot:<main|nose>
#                 <number|name|type>:<value> [<operator:value>]
# where value can be comma separated list of values (no spaces).
# keywords are case insensitive, so eny of DEP,dep,DeP and so on works.
# Examples:
# dep:24 type:1,5,7 operator:JFG,KNS,KSH
# arr:15 number:JS165
# DEP:27L name:A319 operator:AAN
#

class GroundRoute
    attr_reader :name
    attr_reader :runway
    attr_reader :spot
    attr_reader :tail_number
    attr_reader :plane_name
    attr_reader :aircraft_type
    attr_reader :operator
    attr_reader :stand
    attr_reader :filename
    attr_reader :points
    
    def initialize(node, document)
        @name = node.attribute('name').to_s
        parse_name
        @object = node.parent
        @document = document
        read_points @object.css('child')
    end
    
    private
    
    def read_points(node_references)
        @points = []
        node_references.each do |ref|
            id = ref.attribute('id').to_s
            node = @document.css('object[id="' + id + '"]').first
            @points << RoutePoint.new(node)
        end
    end
    
    def parse_name
        @runway = parse_runway
        @spot = parse_spot
        @tail_number = parse_tail_number
        @plane_name = parse_plane_name unless @tail_number
        @aircraft_type = parse_aircraft_type unless @tail_number || @plane_name
        @operator = parse_operators unless @tail_number
        @stand = parse_stand_name
        @filename = parse_file_name
    end
    
    def parse_runway
       match = @name.match(/^(dep|arr)\p{Blank}*:\p{Blank}*(\p{Digit}+[LRC]?)/i)
       (match.present? && match[2]).present? ? match[2].upcase : ''
    end
    
    def parse_spot
        match = @name.match(/spot\p{Blank}*:\p{Blank}*nose/i)
        match.present? ? 'NOSEWHEEL' : 'MAINWHEEL'
    end
    
    def parse_tail_number
        match = @name.match(/number\p{Blank}*:\p{Blank}*(\S+)/i)
        match[1] if match.present? && match[1].present?
    end
    
    def parse_plane_name
        match = @name.match(/name\p{Blank}*:\p{Blank}*(\S+)/i)
        match[1] if match.present? && match[1].present?
    end
    
    def parse_aircraft_type
        match = @name.match(/type\p{Blank}*:\p{Blank}*(\S+)/i)
        types = '0 1 2 3 4 5 6 7 8' # all types
        types = match[1].gsub(',', ' ') if match && match[1]
    end
    
    def parse_operators
        match = @name.match(/operator\p{Blank}*:\p{Blank}*(\S+)/i)
        match[1].gsub(',', ' ').upcase if match && match[1]
    end
    
    def parse_stand_name
        match = @name.match(/stand\p{Blank}*:\p{Blank}*(\S+)/i)
        match[1] if match.present? && match[1].present?
    end
    
    def parse_file_name
        filename = "DEP#{@runway}"
        filename += "_#{@stand}" if @stand
        filename += "_#{@tail_number}" if @tail_number
        filename += "_#{@plane_name}" if @plane_name
        filename += "_#{@aircraft_type.gsub(' ', '')}" if @aircraft_type
        filename + '.txt'
    end
end

app/models/route_point.rb
# point name
# speed | heading | description | cid | runway/taxiway name
#  -3         -1        taxiway     0        park          
#  20.0       -1        taxiway     0         D
#  20.0       -1         16L        1      16L/34R
#  20         -1         16C        2        toff
#
# -3|-1|taxiway|0|park -- the same as below
#
# speed | heading | description | cid | runway/taxiway name
#  -3       -1       taxiway       0    park               
class RoutePoint
    attr_reader :latitude
    attr_reader :longtitude
    attr_reader :speed
    attr_reader :heading
    attr_reader :description
    attr_reader :cid
    attr_reader :rwy_twy_name
    attr_reader :name
    
    def initialize(node)
        @object = node
        hierarchy = node.css('hierarchy')
        point = node.css('point')

        @name = hierarchy.attribute('name').to_s
        @latitude = point.attribute('latitude').to_s
        @longtitude = point.attribute('longitude').to_s
        
        parse_name
    end
    
    private
    
    def parse_name
        match = name.split('|')
        @speed = match[0]
        @heading = match[1] if match[1]
        @description = match[2] if match[2]
        @cid = match[3] if match[3]
        @rwy_twy_name = match[4] if match[4]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ground_routes_controller.rb
require 'zip'

class GroundRoutesController < ApplicationController
  def index
  end
  
  def import
    @airport = Airport.new(params[:file])
    
    @airport.ground_routes.each do |route|
      content = render_to_string(partial: "ground_routes/out.txt",
                                 locals: {route: route})
      filename = Rails.root.join('public', 'files', route.filename)
      
      file = File.open(filename, 'w')
      file.write(content) unless file.nil?
      file.close unless file.nil?
      
    end  
      
    if @airport.ground_routes.any?
      zipfilename = 'ground_routes_' + Time.now.to_i.to_s + '.zip'
      #temp_file = Tempfile.new(zipfilename)
      zipfilepath = Rails.root.join('public', 'zip', zipfilename)
      input_filenames = @airport.ground_routes.map { |route| route.filename }

      Zip::File.open(zipfilepath, Zip::File::CREATE) do |zipfile|
        input_filenames.each do |filename|
          # Two arguments:
          # - The name of the file as it will appear in the archive
          # - The original file, including the path to find it
          filepath = Rails.root.join('public', 'files', filename)
          zipfile.add(filename, filepath)
        end
        zipfile.get_output_stream("myFile") { |os| os.write "myFile contains just this" }
      end
      #  temp_file.close
      #  temp_file.unlink
      
      zip_data = File.read(zipfilepath)
      return send_data(zip_data, :type => 'application/zip', :filename => zipfilename)
    end  
    

    render :index, content_type: 'text/html'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ground_routes/_out.txt.erb
<%if route.tail_number%>
STARTTAILNUM
<%=route.tail_number%>
ENDTAILNUM
<%end%>
<%if route.plane_name%>

STARTAIRCRAFT
<%=route.plane_name%>
ENDAIRCRAFT
<%end%>
<%if route.aircraft_type%>

STARTAIRCRAFTTYPE
<%=route.aircraft_type%>
ENDAIRCRAFTTYPE
<%end%>
<%if route.operator%>

STARTOPERATOR
<%=route.operator%>
ENDOPERATOR
<%end%>

STARTRUNWAY
<%=route.runway%>
ENDRUNWAY

START_PARKING_CENTER
<%=route.spot%>
END_PARKING_CENTER

STARTSTEERPOINTS
<%route.points.each do |point|%>
<%=point.latitude%> <%=point.longtitude%> <%=point.speed%> <%=point.heading%> <%=point.description%> <%=point.cid%> <%=point.rwy_twy_name%>
<%end%>
ENDSTEERPOINTS

app/views/ground_routes/index.html.erb
<%=form_tag(ground_routes_import_path, method: "post", multipart: true) do%>
    <%= file_field_tag "file" %>
    <%= submit_tag %>
<%end%>

<% @airport.ground_routes.each do |route| %>
<section>
    <h1>Route name: <%=route.name%></h1>
    <h2>File name: <%=route.filename%></h2>

    <%if route.tail_number%>
    <code>
        STARTTAILNUM<br/>
        <%=route.tail_number%><br/>
        ENDTAILNUM<br/><br/>
    </code>
    <%end%>
    
    <%if route.plane_name%>
    <code>
        STARTAIRCRAFT<br/>
        <%=route.plane_name%><br/>
        ENDAIRCRAFT<br/><br/>
    </code>
    <%end%>
    
    <%if route.aircraft_type%>
    <code>
        STARTAIRCRAFTTYPE<br/>
        <%=route.aircraft_type%><br/>
        ENDAIRCRAFTTYPE<br/><br/>
    </code>
    <%end%>
    
    <%if route.operator%>
    <code>
        STARTOPERATOR<br/>
        <%=route.operator%><br/>
        ENDOPERATOR<br/><br/>
    </code>
    <%end%>
    
    <code>
        STARTRUNWAY<br/>
        <%=route.runway%><br/>
        ENDRUNWAY<br/><br/>
    </code>
    
    <code>
        START_PARKING_CENTER<br/>
        <%=route.spot%><br/>
        END_PARKING_CENTER<br/><br/>
    </code>

    
    <table>
        <tr>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Speed</th>
            <th>Heading</th>
            <th>Description</th>
            <th>CID</th>
            <th>Rwy/Twy Name</th>
        </tr>
    </table>
    <table>
    <code>
    STARTSTEERPOINTS<br/>
    <table>
    <%route.points.each do |point|%>
        <tr>
            <td><%=point.latitude%></td>
            <td><%=point.longtitude%></td>
            <td><%=point.speed%></td>
            <td><%=point.heading%></td>
            <td><%=point.description%></td>
            <td><%=point.cid%></td>
            <td><%=point.rwy_twy_name%></td>
            <td></td>
        </tr>
    <%end%>
    </table>
    ENDSTEERPOINTS</br/>
    </code>
</section>
<% end if @airport.present? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>